spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC

    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30
      max-request-size: 30


mybatis:
  type-aliases-package: com.wdd.studentmanger.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

